### ISSUE TITLE
question about the dataset: are there some way to access the raw frames

### ISSUE THREAD

**Issue by ValMystletainn** [robincourant/DIRECTOR#1]
as mentioned in the title. Are the any ways or plans to get the access to the raw frames that processed as the char and camera sequences. I think it would be helpful if we can access those video data

**Comment by robincourant** [comment]
Hi, 

Thank you for your interest in our work. 
We will soon release the data extraction code for E.T. [here](https://github.com/robincourant/the-exceptional-trajectories). Additionally, we will provide a script to extract the corresponding frames from an already downloaded version of the [CondensedMovies dataset](https://github.com/m-bain/CondensedMovies).

**Comment by ValMystletainn** [comment]
> Hi,
> 
> Thank you for your interest in our work. We will soon release the data extraction code for E.T. [here](https://github.com/robincourant/the-exceptional-trajectories). Additionally, we will provide a script to extract the corresponding frames from an already downloaded version of the [CondensedMovies dataset](https://github.com/m-bain/CondensedMovies).

Great. thanks for your grea work and answering

**Comment by robincourant** [comment]
Hi, 
I updated the [data extraction repository](https://github.com/robincourant/the-exceptional-trajectories), you can check the "E.T. frames extraction" section.
