### ISSUE TITLE
Training And Evaluation time

### ISSUE THREAD

**Issue by AdityaDhaulakhandi** [robincourant/DIRECTOR#4]
Hi, thanks for the great work. Can you please tell the training and evaluation time for pure and mixed datasets? Also, the peak memory requirements. 
Thanks!

**Comment by robincourant** [comment]
Hi, 

It takes around 20GB to train with a batch size of 64 and half precision. 
The training takes around 13 hours and the evaluation 3h (it depends on the architecture, cross-attention takes the most).

**Comment by AdityaDhaulakhandi** [comment]
Thanks! 
Just a small doubt: In the config file, the num_train_epochs is set to 4001, and the checkpoints downloaded are named 
ca-pure-e989.cpkt, so are these trained for 989 epochs? Can you please clarify?
(I believe for 4000 epochs, the training will take more time.)

**Comment by robincourant** [comment]
Indeed, yet the model converges before the 4001 epochs: around 800! (it is just a random value)
