### ISSUE TITLE
Evaluating text-camera coherence 

### ISSUE THREAD

**Issue by AdityaDhaulakhandi** [robincourant/DIRECTOR#5]
Hi, can you point me to the code where motion tagging is performed for a generated trajectory to derive Classifier Precision (C-P), Classifier Recall (C-R) and Classifier F1-Score (C-F1)?
Thanks!

**Comment by robincourant** [comment]
Hi, 
You'll find the metric code in: https://github.com/robincourant/DIRECTOR/blob/main/src/metrics/modules/caption.py
