### ISSUE TITLE
Camera Rotation Parameters

### ISSUE THREAD

**Issue by AdityaDhaulakhandi** [robincourant/DIRECTOR#7]
Hi, can you describe (or point me to any article) the representation used for rotation parameters? The data dimensionality is [300,9]; the first 3 are for XYZ positions, and the last 6 describe the rotation parameters, right? Thanks!

**Comment by robincourant** [comment]
Hi, 

The 3 components are indeed the translation, and the last 6 correspond to the rotation in the 6d continuous representation from this [paper](https://arxiv.org/pdf/1812.07035).

**Comment by YuiLu** [comment]
Checked the code. Dimensions 1 to 6 are for rotation, and dimensions 7 to 9 are for translation.
