### ISSUE TITLE
pytorch-lightning

### ISSUE THREAD

**Issue by maoning123ab** [robincourant/DIRECTOR#8]
Could you tell me your PyTorch Lightning version? When using PyTorch Lightning, loading each batch of data takes a long time. This becomes less of an issue after the first epoch, but it slows down again after running validation

**Comment by robincourant** [comment]
Hi, 

I'm using `lightning==2.3.3`. 
I’ve noticed the behaviour you’re describing during the first epoch after rebooting my machine (every time), but then, once the first epoch is done I never encounter it again, even when relaunching a new training. I always assumed it had something to do with caching the data or something similar.

**Comment by maoning123ab** [comment]
Thank you for your response. This issue may be related to PyTorch Lightning itself. The problem has already been raised by others, but no effective solution has been found yet.
